version: "3"

services:
    app:
      build:
        context: .
      ports:
        # map port 8000 of host to 8000 of docker
        - "8000:8000"
      volumes:
        # map directory of host in directory of docker
        - ./app:/app
      # shell run command
      command: >
        sh -c "python manage.py runserver 0.0.0.0:8000"
      environment:
        - DB_HOST=db
        - DB_NAME=app
        - DB_USER=postgres
        - DB_PASS=passwordsupercalifragilistichespiralidosa
      depends_on:
        - db

    db:
      image: postgres:10-alpine
      environment:
        - POSTGRES_DB=app
        - POSTGRES_USER=postgres
        # use encrypted environment variable for password in production
        - POSTGRES_PASSWORD=passwordsupercalifragilistichespiralidosa
